### ISSUE TITLE
When duplicating a new tab Sorry, this page isn't available error

### ISSUE THREAD

**Issue by jeanjmnez** [ainielse/majamizer#3]
Hi, I',m trying to use the plugin but i keep getting the error below 

Sorry, this page isn't available
ERR-7620 Could not determine workspace for application ().

Contact your application administrator.

This happens when you duplicate an existing tab in the browser.

**Comment by ainielse** [comment]
Hi,

Are you using friendly URLs? 

If so, I haven’t released a version for that yet. I’ll get to work on it though. 

If not, please paste in the URL you have when you see the error. 

Thanks,

Anton

**Comment by jeanjmnez** [comment]
I'm not using friendly url, the url is this:
http://server:9003/apex/apex_bcrd/r/sistema-gestion-de-efectivo/home?session=5330440348668

rendered url

http://server:9003/apex/f?session=5330440348668::APEX_CLONE_SESSION

When I click the duplicate tab option is when  the error happens

**Comment by ainielse** [comment]
You are using friendly URLs. This is listed in the readme as the first issue. I’ll try to get an update available soon.

**Comment by jeanjmnez** [comment]
Hi thanks for your help i'm new to apex and didn't know much about that, you are right, what i do for now is to disable the friendly url in the application. I think that the documentation could be more specific regarding that if friendly url is enabled should be disabled.

**Comment by jeanjmnez** [comment]
I will close this becuase is not an issue, this is going to be addressed in the next version of the plugin.

**Comment by jeanjmnez** [comment]
This will be fix in a new version of the plugin.
